# Generated by Django 6.0.2 on 2026-04-17 12:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_name', models.CharField(blank=True, max_length=100, verbose_name='Ваше имя')),
                ('hero_profession', wagtail.fields.RichTextField(blank=True, verbose_name='Профессия')),
                ('hero_button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст на кнопке')),
                ('hero_button_link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка для кнопки (можно #section-form-back)')),
                ('projects_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции проектов')),
                ('projects', wagtail.fields.StreamField([('project', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название проекта', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание проекта'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение проекта'}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ссылка на проект', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Смотреть проект', 'help_text': 'Текст на кнопке', 'max_length': 50}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('link', 3), ('button_text', 4)]], {})}, verbose_name='Проекты')),
                ('templates_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции шаблонов')),
                ('templates', wagtail.fields.StreamField([('template', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название шаблона', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание шаблона'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Превью шаблона'}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Ссылка на шаблон', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('link', 3)]], {})}, verbose_name='Шаблоны')),
                ('education_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции образования')),
                ('education_items', wagtail.fields.StreamField([('education', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название курса/образования', 'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Учебное заведение/платформа', 'max_length': 200}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Год окончания', 'max_length': 20}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('institution', 1), ('year', 2), ('description', 3)]], {})}, verbose_name='Образование')),
                ('skills_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции навыков')),
                ('skills', wagtail.fields.StreamField([('skill', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название навыка', 'max_length': 100}), 1: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Уровень владения (1-100)', 'max_value': 100, 'min_value': 1}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('level', 1)]], {})}, verbose_name='Навыки')),
                ('form_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок формы')),
                ('form_intro', wagtail.fields.RichTextField(blank=True, verbose_name='Текст перед формой')),
                ('form_button_text', models.CharField(default='Отправить', max_length=50, verbose_name='Текст на кнопке')),
                ('form_thank_you', wagtail.fields.RichTextField(blank=True, verbose_name='Сообщение после отправки')),
                ('from_address', models.EmailField(blank=True, default='noreply@portfolio.com', max_length=255, verbose_name='Email отправителя')),
                ('to_address', models.EmailField(blank=True, max_length=255, verbose_name='Email получателя')),
                ('subject', models.CharField(blank=True, default='Новое сообщение с портфолио', max_length=255, verbose_name='Тема письма')),
                ('show_button_up', models.BooleanField(default=True, verbose_name='Показывать кнопку наверх')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_header', models.BooleanField(default=True, verbose_name='Показывать в шапке')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Показывать в подвале')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('vk_url', models.URLField(blank=True, verbose_name='VK')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('mail', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('mastodon_url', models.URLField(blank=True, verbose_name='Mastodon')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Настройки соцсетей',
            },
        ),
    ]
