# Generated by Django 6.0.4 on 2026-05-07 13:37

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        ('wagtailmedia', '0005_alter_media_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_sections', wagtail.fields.StreamField([('hero', 4), ('selected_projects', 8), ('templates', 17), ('education_skills', 30), ('contact_form', 34), ('blog', 37)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ваше имя', 'max_length': 100}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Ваша профессия/специализация'}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Текст на кнопке', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Ссылка для кнопки (например, #section-form-back)', 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('profession', 1), ('button_text', 2), ('button_link', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Мои работы', 'help_text': 'Заголовок секции', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу проекта', 'page_type': ['home.ProjectPage']}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Добавьте проекты из списка страниц'}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('projects', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок секции', 'max_length': 200}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название шаблона', 'max_length': 200}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание шаблона'}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Превью шаблона'}), 13: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу шаблона', 'required': False}), 14: ('wagtail.blocks.URLBlock', (), {'blank': True, 'help_text': 'Или внешняя ссылка', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 10), ('description', 11), ('image', 12), ('link_page', 13), ('external_link', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Добавьте шаблоны'}), 17: ('wagtail.blocks.StructBlock', [[('title', 9), ('templates', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Образование', 'max_length': 200, 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название курса/образования', 'max_length': 200}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Учебное заведение/платформа', 'max_length': 200}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Год окончания', 'max_length': 20}), 22: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 19), ('institution', 20), ('year', 21), ('description', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'help_text': 'Образование и курсы', 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Навыки', 'max_length': 200, 'required': False}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название навыка', 'max_length': 100}), 27: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Уровень владения (1-100)', 'max_value': 100, 'min_value': 1}), 28: ('wagtail.blocks.StructBlock', [[('name', 26), ('level', 27)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'help_text': 'Навыки', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('education_title', 18), ('education', 24), ('skills_title', 25), ('skills', 29)]], {}), 31: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Текст перед формой', 'required': False}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'Отправить', 'help_text': 'Текст на кнопке', 'max_length': 50}), 33: ('wagtail.blocks.RichTextBlock', (), {'default': 'Спасибо! Ваше сообщение отправлено.', 'help_text': 'Сообщение после отправки', 'required': False}), 34: ('wagtail.blocks.StructBlock', [[('title', 9), ('intro', 31), ('button_text', 32), ('thank_you_text', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'Блог', 'help_text': 'Заголовок секции', 'max_length': 100}), 36: ('wagtail.blocks.CharBlock', (), {'default': 'Все статьи', 'help_text': 'Текст на кнопке', 'max_length': 50}), 37: ('wagtail.blocks.StructBlock', [[('title', 35), ('button_text', 36)]], {})}, help_text='Добавляйте, удаляйте и меняйте порядок секций перетаскиванием', verbose_name='Секции страницы')),
                ('from_address', models.EmailField(blank=True, default='noreply@portfolio.com', max_length=255, verbose_name='Email отправителя')),
                ('to_address', models.EmailField(blank=True, max_length=255, verbose_name='Email получателя')),
                ('subject', models.CharField(blank=True, default='Новое сообщение с портфолио', max_length=255, verbose_name='Тема письма')),
                ('show_button_up', models.BooleanField(default=True, verbose_name='Показывать кнопку наверх')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PortfolioBlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('posts_per_page', models.IntegerField(default=6, verbose_name='Статей на страницу')),
            ],
            options={
                'verbose_name': 'Блог портфолио (список статей)',
                'verbose_name_plural': 'Блоги портфолио (списки статей)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка на проект',
                'verbose_name_plural': 'Заявки на проекты',
            },
        ),
        migrations.CreateModel(
            name='PortfolioBlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Статья блога портфолио',
                'verbose_name_plural': 'Статьи блога портфолио',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=250, verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('content_block', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок блока', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}, verbose_name='Контент проекта')),
                ('technologies', models.CharField(blank=True, max_length=500, verbose_name='Технологии')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Архив')),
                ('external_link', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('video', models.ForeignKey(blank=True, limit_choices_to={'type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_header', models.BooleanField(default=True, verbose_name='Показывать в шапке')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Показывать в подвале')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('vk_url', models.URLField(blank=True, verbose_name='VK')),
                ('mail', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('mastodon_url', models.URLField(blank=True, verbose_name='Mastodon')),
                ('max_url', models.URLField(blank=True, verbose_name='MAX')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Настройки соцсетей',
            },
        ),
    ]
