# Generated by Django 6.0.4 on 2026-05-08 07:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Текст над формой поиска')),
            ],
            options={
                'verbose_name': 'Страница поиска веб-портфолио',
                'verbose_name_plural': 'Страницы поиска веб-портфолио',
            },
            bases=('wagtailcore.page',),
        ),
    ]
