# Generated by Django 6.0.2 on 2026-04-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='whatsapp',
        ),
    ]
