# Generated by Django 6.0.4 on 2026-05-09 16:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_searchpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Краткое вступление')),
                ('posts_per_page', models.IntegerField(default=6, verbose_name='Проектов на страницу')),
            ],
            options={
                'verbose_name': 'Страница проектов веб-портфолио',
                'verbose_name_plural': 'Страницы проектов веб-портфолио',
            },
            bases=('wagtailcore.page',),
        ),
    ]
