# Generated by Django 6.0.4 on 2026-05-03 10:26

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_socialmediasettings_instagram_url_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioBlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Блог портфолио (список статей)',
                'verbose_name_plural': 'Блоги портфолио (списки статей)',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_button_text',
            field=models.CharField(default='Все статьи', max_length=50, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(default='Блог', max_length=100, verbose_name='Заголовок блока блога'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, verbose_name='WhatsApp'),
        ),
        migrations.CreateModel(
            name='PortfolioBlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение для превью')),
            ],
            options={
                'verbose_name': 'Статья блога портфолио',
                'verbose_name_plural': 'Статьи блога портфолио',
            },
            bases=('wagtailcore.page',),
        ),
    ]
