# Generated by Django 6.0.4 on 2026-05-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_projectslistpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='show_on_main',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы проект появился в блоке «Избранные проекты» на главной странице', verbose_name='Показывать на главной'),
        ),
    ]
