# Generated by Django 6.0.4 on 2026-05-03 11:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_portfolioblogindexpage_homepage_blog_button_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='projects',
            field=wagtail.fields.StreamField([('project', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название проекта', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание проекта'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение проекта'}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу проекта (если есть)', 'required': False, 'verbose_name': 'Ссылка на страницу проекта'}), 4: ('wagtail.blocks.URLBlock', (), {'blank': True, 'help_text': 'Или укажите внешнюю ссылку (например, https://example.com)', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Смотреть проект', 'help_text': 'Текст на кнопке', 'max_length': 50}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('link_page', 3), ('external_link', 4), ('button_text', 5)]], {})}, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='templates',
            field=wagtail.fields.StreamField([('template', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название шаблона', 'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание шаблона'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Превью шаблона'}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу шаблона', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'blank': True, 'help_text': 'Или внешняя ссылка', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('link_page', 3), ('external_link', 4)]], {})}, verbose_name='Шаблоны'),
        ),
    ]
