# Generated by Django 6.0.4 on 2026-05-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_projects_alter_homepage_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='max_url',
            field=models.URLField(blank=True, help_text='Ссылка на ваш профиль в MAX (например, https://max.me/username)', verbose_name='MAX'),
        ),
    ]
