# Generated by Django 6.0.4 on 2026-05-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_projectpage_show_on_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='show_on_main',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='is_ready',
            field=models.BooleanField(default=False, help_text='Отметьте, если проект полностью готов к показу', verbose_name='Проект готов'),
        ),
    ]
