# Generated by Django 6.0.4 on 2026-05-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_projectpage_is_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='github_link',
            field=models.URLField(blank=True, help_text='Ссылка на репозиторий проекта', verbose_name='Ссылка на GitHub'),
        ),
    ]
