# Generated by Django 6.0.4 on 2026-05-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_socialmediasettings_max_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioblogindexpage',
            name='posts_per_page',
            field=models.IntegerField(default=3, help_text='Количество статей, отображаемых на одной странице', verbose_name='Статей на страницу'),
        ),
    ]
