# Generated by Django 6.0.4 on 2026-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_portfolioblogindexpage_posts_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioblogindexpage',
            name='posts_per_page',
            field=models.IntegerField(default=6, help_text='Количество статей, отображаемых на одной странице', verbose_name='Статей на страницу'),
        ),
    ]
