# Generated by Django 6.0.4 on 2026-05-13 10:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_projectpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='content',
            field=wagtail.fields.StreamField([('content_block', 3), ('tabs_block', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок блока', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Отображается над вкладками', 'label': 'Заголовок блока', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Редактирование меню', 'label': 'Название вкладки', 'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Текст, который будет внутри вкладки', 'label': 'Содержимое вкладки', 'required': True}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Загрузите SVG файл', 'label': 'SVG иконка', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('content', 6), ('icon_svg', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'help_text': 'Добавьте от 2 до 5 вкладок', 'label': 'Вкладки'}), 10: ('wagtail.blocks.StructBlock', [[('title', 4), ('tabs', 9)]], {})}, verbose_name='Контент проекта'),
        ),
    ]
