# Generated by Django 6.0.4 on 2026-05-06 07:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_projectrequest'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        ('wagtailmedia', '0005_alter_media_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Страница проектов',
                'verbose_name_plural': 'Страницы проектов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='use_selected_projects',
            field=models.BooleanField(default=False, help_text='Включите, чтобы показывать проекты из списка выше, выключите — вернётесь к StreamField', verbose_name='Использовать выбранные проекты вместо StreamField'),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=250, verbose_name='Краткое описание')),
                ('content', wagtail.fields.StreamField([('content_block', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок блока', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}, verbose_name='Контент проекта')),
                ('technologies', models.CharField(blank=True, help_text='Перечислите технологии через запятую (например: Python, Django, Wagtail)', max_length=500, verbose_name='Технологии')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('is_published', models.BooleanField(default=False, help_text='Показывать проект на сайте', verbose_name='Опубликовано')),
                ('is_archive', models.BooleanField(default=False, help_text='Проект завершён, но не продан (показывается только на странице всех проектов)', verbose_name='Архив')),
                ('external_link', models.URLField(blank=True, help_text='Если проект продан, укажите ссылку на сайт заказчика', verbose_name='Внешняя ссылка')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение для превью')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Ссылка на страницу сайта')),
                ('video', models.ForeignKey(blank=True, limit_choices_to={'type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Видео проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='selected_projects',
            field=models.ManyToManyField(blank=True, help_text='Выберите проекты для отображения на главной', to='home.projectpage', verbose_name='Выбранные проекты (из страниц)'),
        ),
    ]
