# Generated by Django 6.0.4 on 2026-05-14 17:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_projectpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='content',
            field=wagtail.fields.StreamField([('content_block', 3), ('tabs_block', 16), ('carousel_block', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок блока', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Описание', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Отображается над вкладками', 'label': 'Заголовок блока', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Редактирование меню', 'label': 'Название вкладки', 'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Текст, который будет внутри вкладки', 'label': 'Содержимое вкладки', 'required': True}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Загрузите SVG файл', 'label': 'SVG иконка', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('image', 'Изображение'), ('gif', 'GIF-анимация'), ('video', 'Видео')], 'label': 'Тип медиа'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Загрузите JPG, PNG или GIF', 'label': 'Изображение или GIF', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': 'YouTube, Vimeo или прямой URL', 'label': 'Ссылка на видео', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Краткое описание', 'label': 'Подпись', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('media_type', 8), ('image', 9), ('video_url', 10), ('caption', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Добавьте изображения, GIF или видео для этой вкладки', 'label': 'Медиа галерея', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 5), ('content', 6), ('icon_svg', 7), ('gallery', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'help_text': 'Добавьте от 2 до 5 вкладок', 'label': 'Вкладки'}), 16: ('wagtail.blocks.StructBlock', [[('title', 4), ('tabs', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Как выглядит сайт', 'label': 'Заголовок блока', 'required': False}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Краткое описание скриншота', 'label': 'Подпись', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('image', 18), ('caption', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'help_text': 'Добавьте скриншоты сайта (рекомендуется ширина 1200px+)', 'label': 'Слайды'}), 22: ('wagtail.blocks.StructBlock', [[('title', 17), ('slides', 21)]], {})}, verbose_name='Контент проекта'),
        ),
    ]
