# Generated by Django 6.0.4 on 2026-05-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_projectsindexpage_homepage_use_selected_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='selected_projects',
            field=models.ManyToManyField(blank=True, help_text='Выберите проекты для отображения на главной странице', to='home.projectpage', verbose_name='Выбранные проекты'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='use_selected_projects',
            field=models.BooleanField(default=False, help_text='Включите, чтобы показывать выбранные проекты вместо StreamField', verbose_name='Использовать выбранные проекты'),
        ),
    ]
