# Generated by Django 6.0.4 on 2026-05-06 09:02

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_selected_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='selected_projects',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='use_selected_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HomePageSelectedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_projects_items', to='home.homepage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.projectpage', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Выбранный проект',
                'verbose_name_plural': 'Выбранные проекты',
            },
        ),
    ]
