# Generated by Django 6.0.4 on 2026-05-06 09:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homepage_selected_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='blog_button_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blog_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='education_items',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='education_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='form_button_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='form_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='form_thank_you',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='form_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_button_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_profession',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='projects_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='skills_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='templates',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='templates_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_sections',
            field=wagtail.fields.StreamField([('hero', 4), ('projects', 14), ('templates', 22), ('education_skills', 33), ('contact_form', 37), ('blog', 40)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ваше имя', 'max_length': 100}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Ваша профессия/специализация'}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Текст на кнопке', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Ссылка для кнопки', 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('profession', 1), ('button_text', 2), ('button_link', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок секции', 'max_length': 200}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название проекта', 'max_length': 200}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание проекта'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Изображение проекта'}), 9: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу проекта (если есть)', 'required': False, 'verbose_name': 'Ссылка на страницу проекта'}), 10: ('wagtail.blocks.URLBlock', (), {'blank': True, 'help_text': 'Или укажите внешнюю ссылку (например, https://example.com)', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Смотреть проект', 'help_text': 'Текст на кнопке', 'max_length': 50}), 12: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('image', 8), ('link_page', 9), ('external_link', 10), ('button_text', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'help_text': 'Добавьте проекты'}), 14: ('wagtail.blocks.StructBlock', [[('title', 5), ('projects', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название шаблона', 'max_length': 200}), 16: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание шаблона'}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Превью шаблона'}), 18: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу шаблона', 'required': False}), 19: ('wagtail.blocks.URLBlock', (), {'blank': True, 'help_text': 'Или внешняя ссылка', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 15), ('description', 16), ('image', 17), ('link_page', 18), ('external_link', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'help_text': 'Добавьте шаблоны'}), 22: ('wagtail.blocks.StructBlock', [[('title', 5), ('templates', 21)]], {}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название курса/образования', 'max_length': 200}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': 'Учебное заведение/платформа', 'max_length': 200}), 25: ('wagtail.blocks.CharBlock', (), {'help_text': 'Год окончания', 'max_length': 20}), 26: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание', 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('title', 23), ('institution', 24), ('year', 25), ('description', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {'help_text': 'Образование и курсы', 'required': False}), 29: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название навыка', 'max_length': 100}), 30: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Уровень владения (1-100)', 'max_value': 100, 'min_value': 1}), 31: ('wagtail.blocks.StructBlock', [[('name', 29), ('level', 30)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {'help_text': 'Навыки', 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('title', 5), ('education', 28), ('skills', 32)]], {}), 34: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Текст перед формой', 'required': False}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'Отправить письмо', 'help_text': 'Текст на кнопке', 'max_length': 50}), 36: ('wagtail.blocks.CharBlock', (), {'help_text': 'Текст после отправки', 'max_length': 200, 'required': False}), 37: ('wagtail.blocks.StructBlock', [[('title', 5), ('intro', 34), ('button_text', 35), ('thank_you_text', 36)]], {}), 38: ('wagtail.blocks.CharBlock', (), {'default': 'Блог', 'help_text': 'Заголовок секции', 'max_length': 100}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Все статьи', 'help_text': 'Текст на кнопке', 'max_length': 50}), 40: ('wagtail.blocks.StructBlock', [[('title', 38), ('button_text', 39)]], {})}, help_text='Добавляйте, удаляйте и меняйте порядок секций перетаскиванием', verbose_name='Секции страницы'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='use_selected_projects',
            field=models.BooleanField(default=False, verbose_name='Использовать выбранные проекты'),
        ),
    ]
