# Generated by Django 6.0.4 on 2026-05-07 07:59

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_homepage_blog_button_text_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        ('wagtailmedia', '0005_alter_media_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='use_selected_projects',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='page_sections',
            field=wagtail.fields.StreamField([('hero', 4), ('selected_projects', 8), ('templates', 17), ('education_skills', 30), ('contact_form', 34), ('blog', 37)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ваше имя', 'max_length': 100}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Ваша профессия/специализация'}), 2: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Текст на кнопке', 'max_length': 50, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'blank': True, 'help_text': 'Ссылка для кнопки (например, #section-form-back)', 'max_length': 200, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('profession', 1), ('button_text', 2), ('button_link', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Мои работы', 'help_text': 'Заголовок секции', 'max_length': 200, 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу проекта', 'page_type': ['home.ProjectPage']}), 7: ('wagtail.blocks.ListBlock', (6,), {'help_text': 'Добавьте проекты из списка страниц'}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('projects', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Заголовок секции', 'max_length': 200}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название шаблона', 'max_length': 200}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание шаблона'}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Превью шаблона'}), 13: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Выберите страницу шаблона', 'required': False}), 14: ('wagtail.blocks.URLBlock', (), {'blank': True, 'help_text': 'Или внешняя ссылка', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 10), ('description', 11), ('image', 12), ('link_page', 13), ('external_link', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'help_text': 'Добавьте шаблоны'}), 17: ('wagtail.blocks.StructBlock', [[('title', 9), ('templates', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Образование', 'max_length': 200, 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название курса/образования', 'max_length': 200}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Учебное заведение/платформа', 'max_length': 200}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Год окончания', 'max_length': 20}), 22: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Описание', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 19), ('institution', 20), ('year', 21), ('description', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'help_text': 'Образование и курсы', 'required': False}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'Навыки', 'max_length': 200, 'required': False}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': 'Название навыка', 'max_length': 100}), 27: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Уровень владения (1-100)', 'max_value': 100, 'min_value': 1}), 28: ('wagtail.blocks.StructBlock', [[('name', 26), ('level', 27)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'help_text': 'Навыки', 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('education_title', 18), ('education', 24), ('skills_title', 25), ('skills', 29)]], {}), 31: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic'], 'help_text': 'Текст перед формой', 'required': False}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'Отправить', 'help_text': 'Текст на кнопке', 'max_length': 50}), 33: ('wagtail.blocks.RichTextBlock', (), {'default': 'Спасибо! Ваше сообщение отправлено.', 'help_text': 'Сообщение после отправки', 'required': False}), 34: ('wagtail.blocks.StructBlock', [[('title', 9), ('intro', 31), ('button_text', 32), ('thank_you_text', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'Блог', 'help_text': 'Заголовок секции', 'max_length': 100}), 36: ('wagtail.blocks.CharBlock', (), {'default': 'Все статьи', 'help_text': 'Текст на кнопке', 'max_length': 50}), 37: ('wagtail.blocks.StructBlock', [[('title', 35), ('button_text', 36)]], {})}, help_text='Добавляйте, удаляйте и меняйте порядок секций перетаскиванием', verbose_name='Секции страницы'),
        ),
        migrations.AlterField(
            model_name='portfolioblogindexpage',
            name='posts_per_page',
            field=models.IntegerField(default=6, verbose_name='Статей на страницу'),
        ),
        migrations.AlterField(
            model_name='portfolioblogpostpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='portfolioblogpostpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='technologies',
            field=models.CharField(blank=True, max_length=500, verbose_name='Технологии'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='video',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='max_url',
            field=models.URLField(blank=True, verbose_name='MAX'),
        ),
        migrations.DeleteModel(
            name='HomePageSelectedProject',
        ),
        migrations.DeleteModel(
            name='ProjectsIndexPage',
        ),
    ]
