# Generated by Django 6.0.2 on 2026-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafepage',
            name='show_contacts_section',
            field=models.BooleanField(default=False, verbose_name='Показывать секцию контактов'),
        ),
    ]
