# Generated by Django 6.0.2 on 2026-04-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_alter_cafepage_show_contacts_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemprice',
            options={'ordering': ['-id'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
    ]
