# Generated by Django 6.0.2 on 2026-04-26 09:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_itemprice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafepage',
            name='gallery_carousel',
            field=wagtail.fields.StreamField([('gallery_slide', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок на странице', 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'label': 'Описание', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1), ('description', 2)]], {})}, verbose_name='Слайды галереи'),
        ),
    ]
