# Generated by Django 6.0.4 on 2026-05-07 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_metrika_id', models.CharField(blank=True, help_text='Вставьте только цифровой ID (например, 12345678)', max_length=50, verbose_name='ID Яндекс.Метрики')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Настройки аналитики',
                'verbose_name_plural': 'Настройки аналитики',
            },
        ),
    ]
