# Generated by Django 6.0.4 on 2026-06-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssettings',
            name='yandex_webmaster_id',
            field=models.CharField(blank=True, help_text='ID сайта в Яндекс.Вебмастере', max_length=100),
        ),
    ]
