# Generated by Django 6.0.4 on 2026-05-07 13:37

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Вступительный текст')),
            ],
            options={
                'verbose_name': 'Страница блога для фотостудии',
                'verbose_name_plural': 'Страницы блога для фотостудии',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPortfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Краткое вступление на странице портфолио (можно оставить пустым)')),
            ],
            options={
                'verbose_name': 'Страница портфолио фотостудии',
                'verbose_name_plural': 'Страницы портфолио фотостудии',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Короткое описание под заголовком')),
                ('name_and_inn', models.CharField(blank=True, default='ИП Северный свет · ИНН 1234567890', max_length=50, verbose_name='Наименование юрюлица и ИНН')),
                ('address', models.CharField(blank=True, default='Санкт-Петербург, Невский проспект, д. 10', max_length=200, verbose_name='Адрес')),
                ('map_iframe', models.TextField(blank=True, help_text='Скопируйте готовый iframe код карты из Яндекс.Карт', verbose_name='Код карты (iframe)')),
            ],
            options={
                'verbose_name': 'Страница Контакты-фотостудии',
                'verbose_name_plural': 'Страницы Контакты-фотостудии',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogAboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('mini_title', models.CharField(default='Подзаголовок', max_length=200)),
                ('content_blocks', wagtail.fields.StreamField([('text_block', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текстовый блок', 'required': True})}, verbose_name='Блоки контента')),
                ('team_title', models.CharField(default='Команда', max_length=100)),
                ('team_subtitle', models.CharField(default='Люди, которые создают эту красоту', max_length=200)),
                ('team_members', wagtail.fields.StreamField([('member', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Имя', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Должность', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фото', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('position', 1), ('description', 2), ('photo', 3)]], {})}, verbose_name='Члены команды')),
                ('footer_text', wagtail.fields.RichTextField(blank=True)),
                ('main_image', models.ForeignKey(blank=True, help_text='Главное изображение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Страница О студии',
                'verbose_name_plural': 'Страницы О студии',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('studio_name', models.CharField(default='СЕВЕРНЫЙ СВЕТ', help_text='Название студии (по центру)', max_length=100)),
                ('studio_tagline', models.CharField(default='архитектура · интерьеры · события · детали', help_text='Короткое описание под названием', max_length=200)),
                ('phone_text', models.CharField(default='+7 999 123-45-67', help_text='Номер телефона', max_length=20)),
                ('photo_credit', models.CharField(default='Фото: Freepik', help_text='Подпись об авторстве фото', max_length=100)),
                ('category_1_name', models.CharField(default='Отели', help_text='Название первой категории', max_length=50, verbose_name='Категория 1')),
                ('category_2_name', models.CharField(default='Фасады', max_length=50, verbose_name='Категория 2')),
                ('category_3_name', models.CharField(default='События', max_length=50, verbose_name='Категория 3')),
                ('category_4_name', models.CharField(default='Детали', max_length=50, verbose_name='Категория 4')),
                ('background_image', models.ForeignKey(blank=True, help_text='Фоновое изображение на всю страницу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('portfolio_page', models.ForeignKey(blank=True, help_text='Страница, на которую будут вести категории (обычно /portfolio/)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Страница портфолио')),
            ],
            options={
                'verbose_name': 'Главная страница фотостудии',
                'verbose_name_plural': 'Главные страницы фотостудии',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('intro', models.CharField(blank=True, help_text='Краткое описание', max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Основной текст поста')),
                ('post_image', models.ForeignKey(blank=True, help_text='Главное изображение поста', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, help_text='Подпись к фото', max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blog.blogpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(help_text='Дата проведения съёмки', verbose_name='Дата съёмки')),
                ('category_number', models.IntegerField(choices=[(1, 'Отели'), (2, 'Фасады'), (3, 'События'), (4, 'Детали')], default=1, help_text='Выберите категорию проекта')),
                ('mini_description', wagtail.fields.RichTextField(blank=True, help_text='Описание главного изображения')),
                ('short_description', models.CharField(blank=True, help_text='Краткое описание для карточки проекта', max_length=200)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Полное описание проекта')),
                ('gallery', wagtail.fields.StreamField([('image', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'})}, help_text='Дополнительные фотографии проекта')),
                ('main_image', models.ForeignKey(blank=True, help_text='Главное изображение проекта (будет крупным вверху страницы)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('title_image', models.ForeignKey(blank=True, help_text='Изображение проекта на карточке в портфолио', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Проект в портфолио фотостудии',
                'verbose_name_plural': 'Проекты в портфолио фотостудии',
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
