# Generated by Django 6.0.2 on 2026-04-19 10:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogaboutpage',
            name='content_blocks',
            field=wagtail.fields.StreamField([('text_block', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текстовый блок', 'required': True})}, verbose_name='Блоки контента'),
        ),
    ]
