# Generated by Django 6.0.2 on 2026-04-19 11:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogaboutpage_content_blocks'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Короткое описание под заголовком')),
                ('phone', models.CharField(blank=True, default='+7 999 123-45-67', max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='info@northlight.ru', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='Санкт-Петербург, Невский проспект, д. 10', max_length=200, verbose_name='Адрес')),
                ('map_link', models.URLField(blank=True, default='https://yandex.ru/maps/', help_text='Скопируйте ссылку на карту с меткой из Яндекс.Карт', verbose_name='Ссылка на Яндекс.Карты')),
            ],
            options={
                'verbose_name': 'Страница Контакты-фотостудии',
                'verbose_name_plural': 'Страницы Контакты-фотостудии',
            },
            bases=('wagtailcore.page',),
        ),
    ]
