# Generated by Django 6.0.2 on 2026-04-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contactpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='map_link',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='map_iframe',
            field=models.TextField(blank=True, help_text='Скопируйте готовый iframe код карты из Яндекс.Карт', verbose_name='Код карты (iframe)'),
        ),
    ]
