# Generated by Django 6.0.2 on 2026-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_contactpage_map_link_contactpage_map_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='name_and_inn',
            field=models.CharField(blank=True, default='ИП Северный свет · ИНН 1234567890', max_length=50, verbose_name='Наименование юрюлица и ИНН'),
        ),
    ]
