# Generated by Django 6.0.2 on 2026-04-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contactpage_name_and_inn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='phone',
        ),
    ]
